# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a235a4b2fa5ea4e687b0337439077ed263380a14fbb10729abd3b00631a6c24df7749aa9ff6bdc5de67aa7f6349ea6d1a3f670665748678c9b61b2a7affeb6ad

test:
  secret_key_base: 6303c842e9a0ebd39c60ad1e49076ba8e16a817c87942cd8ff5e16417206e8357f6064b553db1f82eae8ff646a2b48287b0274cca3117035cdf418214129cd57

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
